#### Numpy is a library for scientific computing in python. It offers mathematical functions, random number generators, linear algebra routines, fourier transforms and more. It is widely used in data science and machine learning.

In [1]:
#importing numpy and pandas library
import numpy as np
import pandas as pd

### Creating numpy arrays

In [2]:
# creating numpy 1D array
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [3]:
#numpy arrays can store numeric values to do faster computations
np.array([1,1.0,'array'])
#here in this rthere are different data types. Still the numpy stores it in the format of unicode string array(dtype='<U32')
#if you mix strings you will not able to do faster computations.
# Here everything is converted to strings

array(['1', '1.0', 'array'], dtype='<U32')

In [4]:
#type of array
print(type(a))

<class 'numpy.ndarray'>


In [5]:
#1D array of length 10 with all zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
#2D array of zeros
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [7]:
#5x5 matrix of all ones
print(np.ones((5,5))) #this returns array with float values
print('\n')
# In this by specifying dtype=int you will get integer values rather than float. Default it returns float values
print(np.ones((5,5),dtype=int)) #this returns array with integer values

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [8]:
#5x5 array of zero with 1 on diagonal.
np.eye(5)  #This is identity matrix
#Identity matrix is square matrix so you need to pass single integer in np.eye(). entering tuple may result in type error. np.eye((x,y))error

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
#creating 2D array
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)
print(type(b))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [10]:
#creating 3Darray
c=np.array([[[1,2,3],[45,6,7]],[[4,7,23],[4,76,2]]])
print(type(c))
print(c)

<class 'numpy.ndarray'>
[[[ 1  2  3]
  [45  6  7]]

 [[ 4  7 23]
  [ 4 76  2]]]


In [11]:
#Generating 3 random integers in between 1 and 15
np.random.randint(1,15,3) 
#If we run again, different numbers will be generated 

array([11,  4,  8], dtype=int32)

In [12]:
#Creating 2D array of size 2x3 with random float values
np.random.rand(2,3)

array([[0.52578734, 0.37385131, 0.1208589 ],
       [0.98195966, 0.18204902, 0.17189649]])

In [13]:
#Creating random 2D array of size (4,6) and the integer values are in between 1,15
np.random.randint(1,15,size=(4,6))

array([[ 4,  2, 14,  7, 13,  2],
       [ 8, 12, 11, 10,  3, 11],
       [10,  9, 11, 10,  9, 13],
       [ 8,  9,  7,  6, 11, 12]], dtype=int32)

In [14]:
#Generating identity matrix of 7x7 with integer values
np.eye(7,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1]])

In [15]:
#Generating values from 0 to 15 with step value 3
np.arange(0,15,3)

array([ 0,  3,  6,  9, 12])

In [16]:
# generating numbers from 0 to 11 using arange function and reshaping the array into 3D array of shape (3,2,2)
a=np.arange(12)
a=a.reshape(2,2,3)
print(a)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [17]:
# Transpose of a matrix (rows becomes columns and vice versa)
a.T

array([[[ 0,  6],
        [ 3,  9]],

       [[ 1,  7],
        [ 4, 10]],

       [[ 2,  8],
        [ 5, 11]]])

In [18]:
trans=np.array([(1,2,3,4),(5,6,7,8)])
trans

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
trans.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [20]:
trans.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [21]:
#resize, it changes the array shape to mxn and fills new values with 0
trans.resize((6,6),refcheck=False)
trans

array([[1, 2, 3, 4, 5, 6],
       [7, 8, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [22]:
#size can return number of elements in the array
trans.size

36

In [23]:
arr=np.array([1,2,3,4,5,6,7,8,9])
arr.size

9

In [24]:
#append, it can add values to end of an array
arr2=np.append(arr,[0,1,2,3,41])
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9,  0,  1,  2,  3, 41])

In [25]:
#insert, it will insert the value 33 at index 2 in arr2
np.insert(arr2,2,33)

array([ 1,  2, 33,  3,  4,  5,  6,  7,  8,  9,  0,  1,  2,  3, 41])

In [26]:
trans

array([[1, 2, 3, 4, 5, 6],
       [7, 8, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [27]:
trans1=np.delete(trans,4)
trans1

array([1, 2, 3, 4, 6, 7, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [28]:
np.delete(trans,4,axis=1)

array([[1, 2, 3, 4, 6],
       [7, 8, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [29]:
# abs function returns absolute value
abs(-1)


1

In [30]:
# it adds the element wise
np.add.accumulate(np.array([1,2,3,4]))
#1=1
#1+2=3
#3+3=6
#6+4=10

array([ 1,  3,  6, 10])

In [31]:
#np.add.accumulate is same as np.cumsum
np.cumsum(np.array([1,2,3,4]))

array([ 1,  3,  6, 10])

In [32]:
#it multiply elementwise
np.multiply.accumulate(np.array([1,2,3,4]))
#1=1
#1*2=2
#2*3=6
#6*4=24

array([ 1,  2,  6, 24])

In [33]:
from numpy import *

In [34]:
#addition of elements in row wise. first row remains same. then second row changes as 1+4,2+5,3+6
add.accumulate(array([[1,2,3],[4,5,6]]),axis=0)

array([[1, 2, 3],
       [5, 7, 9]])

In [35]:
#addition happens column wise. first column remains same
add.accumulate(array([[1,2,3],[4,5,6]]),axis=1)

array([[ 1,  3,  6],
       [ 4,  9, 15]])

In [36]:
# if we do direct addition like this, it concatenates the lists
[-1.2,1.2]+[1,3]

[-1.2, 1.2, 1, 3]

In [37]:
#adding two arrays
add(array([-1.2,1.2]),array([1,3]))

array([-0.2,  4.2])

In [38]:
#adding two arrays
array([-1.2,1.2])+array([1,3])

array([-0.2,  4.2])

In [39]:
#generates exactly five equally spaced values
np.linspace(0,150,5)

array([  0. ,  37.5,  75. , 112.5, 150. ])

In [40]:
#generates values from 0 to 150 with equal step value 5
np.arange(0,150,5)

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145])

In [41]:
#If all are true it returns true. all() means , it says all need to be true. It is like AND condition
a=np.array([True,False,True])
a.all()

np.False_

In [42]:
#If any one is true it returns true. any() means, it says any one need to be true. it is like OR operator
a.any()

np.True_

In [43]:
#compare both arrays are approximately close or not
allclose(array([1e10,1e-7]), array([1.00001e10,1e-8]))

False

In [44]:
#angle in radians
angle(1+1j)

np.float64(0.7853981633974483)

In [45]:
# angle in degrees
angle(1+1j,deg=True)

np.float64(45.0)

In [46]:
#defining a function
def myfunc(a):
    return (a[0]+a[-1])/2

In [47]:
b=array([[1,2,3],[4,5,6],[7,8,9]])
apply_along_axis(myfunc,0,b)
#apply_along_axis, it applies the function(myfunc) along axis=0, means rows in matrix b. According to the function it takes first and last element 
# of the row and averages it.
#1+7=(8/2)=4
#2+8=(10/2)=5
#9+3=(12/2)=6


array([4., 5., 6.])

<p style="color: yellow;">Syntax: np.apply_along_axis(func1d, axis, arr, *args, **kwargs)</p>
<p style="color: blue;">Applies a function to 1D slices along the specified axis.The function must accept a 1D array and return either a scalar or another 1D array.
</p>



In [48]:
apply_along_axis(myfunc,1,b)
#here same as before one but along the columns axis=1
#1+3=(4/2)=2
#4+6=(10/2)=5
#7+9=(16/2)=8

array([2., 5., 8.])

In [49]:
a=arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

<p style="color: yellow;">syntax: np.apply_over_axes(func, arr, axes)</p>
<p style="color: blue;">Applies a function to the specified axes, but the function must support multidimensional input (like np.sum, np.mean).
Returns an array with the same number of dimensions (unlike apply_along_axis, which can reduce dimensions).</p>

In [50]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])

# Apply sum over axis 1 (rows)
result = np.apply_over_axes(np.sum, arr, axes=[1])
print(result)
#Notice how the result keeps the original number of dimensions (2D) instead of reducing it to 1D.

[[ 6]
 [15]]


<p>Use apply_along_axis() when working with 1D operations (e.g., applying a function to each row or column separately).</p>
<p>Use apply_over_axes() when applying a NumPy function across multiple axes while preserving the shape.</p>

In [51]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])

# Apply sum over axis 1 (rows)
result = np.apply_over_axes(np.sum, arr, axes=0)
print(result)
#Notice how the result keeps the original number of dimensions (2D) instead of reducing it to 1D.

[[5 7 9]]


In [52]:
#arccos() function prints the inverse cosine values
arr = np.array([-1, -0.5, 0, 0.5, 1])
angles = np.arccos(arr)
print(angles)  


[3.14159265 2.0943951  1.57079633 1.04719755 0.        ]


In [53]:
#arccosh() gives inverse hyperbolic values
value = np.arccosh(2)
print(value)  # Output: 1.3169578969248166


1.3169578969248166


In [54]:
#argmax gives the index of the maximum element
a=array([10,20,68,34,25,56])
print(a.argmax())  #returns the maximum value index
print(a[a.argmax()])  #returns the maximum value

2
68


In [55]:
b=array([[1,3,2,5,34,23],[34,5,23,67,4,9]])
max_index=b.argmax()  #reading the maximum element index
print(b.ravel()[max_index])   #flattening the array into 1D and then calling the index to display maximum element

67


In [56]:
#returns the minimum element index, argmin()
print(a.argmin())
print(a[a.argmin()])

0
10


In [57]:
a

array([10, 20, 68, 34, 25, 56])

In [58]:
# indices of sorted array using quicksort (default)
ind = a.argsort()
ind

array([0, 1, 4, 3, 5, 2])

In [59]:
a[ind] #same as a.sort()

array([10, 20, 25, 34, 56, 68])

In [60]:
a.sort()
a

array([10, 20, 25, 34, 56, 68])

In [61]:
abs(array([-1.2,1.2]))

array([1.2, 1.2])

In [62]:
abs(1.2+1j)  #gives the absolute value squareroot(a*a + b*b)

np.float64(1.5620499351813308)

In [63]:
#shape returns the shape of the array
a.shape

(6,)

In [64]:
#converting array to a python list
a.tolist()

[10, 20, 25, 34, 56, 68]

In [65]:
#sorts along the specific axis
a.sort(axis=0)
a

array([10, 20, 25, 34, 56, 68])

In [66]:
concatenate((arr,a),axis=0)

array([-1. , -0.5,  0. ,  0.5,  1. , 10. , 20. , 25. , 34. , 56. , 68. ])

In [67]:
concatenate((trans,trans),axis=1)
#concatenating along the column

array([[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6],
       [7, 8, 0, 0, 0, 0, 7, 8, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [68]:
np.array([11,23,44],dtype=float)

array([11., 23., 44.])

In [69]:
np.array([11,23,44,0],dtype=bool)

array([ True,  True,  True, False])

In [70]:
np.array([11,23,44],dtype=complex)

array([11.+0.j, 23.+0.j, 44.+0.j])

In [71]:
np.random.random((3,4))

array([[0.2271009 , 0.63814263, 0.46605842, 0.25082171],
       [0.59280836, 0.26393347, 0.1603155 , 0.33657246],
       [0.9256847 , 0.89418698, 0.48598593, 0.01401956]])

In [72]:
np.arange(0,150,10)

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120,
       130, 140])

In [73]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [74]:
np.linspace(-2,12,6)

array([-2. ,  0.8,  3.6,  6.4,  9.2, 12. ])

In [75]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [76]:
np.arange(12,dtype=float).reshape(3,4)

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [77]:
a1=np.arange(10)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)
print(a1)
print('\n')
print(a2)
print('\n')
print(a3)

[0 1 2 3 4 5 6 7 8 9]


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [78]:
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)
#ndim says how many dimensions the array have.

1
2
3


In [79]:
print("a1 shape:",a1.shape)
print(f'a2 shape:{a2.shape}')
print("a3 shape:",a3.shape)


a1 shape: (10,)
a2 shape:(3, 4)
a3 shape: (2, 2, 2)


In [80]:
#size gives number of elements in the array
print(f'size of a1: {a1.size}')
print(f'size of a2: {a2.size}')
print(f'size of a3: {a3.size}')

size of a1: 10
size of a2: 12
size of a3: 8


In [81]:
#itemsize gives the memory occupied by the item
print(f'itemsize in a1: {a1.itemsize}')
print(f'itemsize in a2: {a2.itemsize}')
print(f'itemsize in a3: {a3.itemsize}')

itemsize in a1: 8
itemsize in a2: 8
itemsize in a3: 8


In [82]:
#dtype gives the datatype of the items
print(f'datatype of a1: {a1.dtype}')
print(f'datatype of a2: {a2.dtype}')
print(f'datatype of a3: {a3.dtype}')

datatype of a1: int64
datatype of a2: float64
datatype of a3: int64


In [83]:
#Changing data type
a2=a2.astype(int)
print(a2.dtype)
print(a2)

int64
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### Array operations

In [84]:
z1=np.arange(12).reshape(3,4)
z2=np.arange(12,24).reshape(3,4)

In [85]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [86]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [87]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [88]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

#### Scalar operations

In [89]:
z1+2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [90]:
z1-2

array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [91]:
z1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [92]:
z1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [93]:
z1%2

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]])

#### relational operations

In [94]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [95]:
z2>2

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [96]:
z2[z2>2]

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [97]:
z2<20

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [False, False, False, False]])

#### Vector operations

In [98]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [99]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [100]:
z1+z2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [101]:
z1-z2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [102]:
z1*z2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [103]:
z1/z2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

#### Array functions

In [104]:
k1=random.random((3,3))   #generates values in between 0 and 1
k1=np.round(k1*100)      # it rounds the values to nearest integer. First multiply the number with 100 and then rounds it off.
k1

array([[45., 27., 33.],
       [ 2., 29., 38.],
       [62., 15., 41.]])

In [105]:
print(max(k1))

62.0


In [106]:
print(min(k1))

2.0


In [107]:
print(sum(k1))

292.0


In [108]:
print(prod(k1))

3369524459400.0


In [109]:
k1

array([[45., 27., 33.],
       [ 2., 29., 38.],
       [62., 15., 41.]])

In [110]:
max(k1,axis=0)

array([62., 29., 41.])

In [111]:
max(k1,axis=1)

array([45., 38., 62.])

In [112]:
prod(k1,axis=1)

array([40095.,  2204., 38130.])

#### statistics related functions

In [113]:
k1

array([[45., 27., 33.],
       [ 2., 29., 38.],
       [62., 15., 41.]])

In [114]:
print(mean(k1))

32.44444444444444


In [115]:
print(mean(k1,axis=0))

[36.33333333 23.66666667 37.33333333]


In [116]:
print(median(k1))

33.0


In [117]:
print(median(k1,axis=0))

[45. 27. 38.]


In [118]:
k1

array([[45., 27., 33.],
       [ 2., 29., 38.],
       [62., 15., 41.]])

In [119]:
print(std(k1))

16.35788026956978


In [120]:
std(k1,axis=0)

array([25.24986249,  6.18241233,  3.29983165])

In [121]:
var(k1)

np.float64(267.5802469135803)

In [122]:
print(var(k1,axis=1))

[ 56.         234.         369.55555556]


#### Trigonometry functions

In [123]:
sin(k1)

array([[ 0.85090352,  0.95637593,  0.99991186],
       [ 0.90929743, -0.66363388,  0.29636858],
       [-0.7391807 ,  0.65028784, -0.15862267]])

In [124]:
cos(k1)

array([[ 0.52532199, -0.29213881, -0.01327675],
       [-0.41614684, -0.74805753,  0.95507364],
       [ 0.67350716, -0.75968791, -0.98733928]])

In [125]:
tan(k1)

array([[  1.61977519,  -3.2737038 , -75.3130148 ],
       [ -2.18503986,   0.88714284,   0.31030966],
       [ -1.09750978,  -0.8559934 ,   0.1606567 ]])

#### Dot product

In [126]:
s2=np.arange(12).reshape(3,4)
s3=np.arange(12,24).reshape(4,3)

In [127]:
print(s2)
print(s3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [128]:
#dot product is similar to the matrix multiplication
dot(s2,s3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [129]:
# '@' symbol is used to multiply matrices
s2@s3

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [130]:
#matmul , it multiplies the matrices, same as dot product
matmul(s2,s3)   #for 1D arrays it throws error

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [131]:
# 'exp' provides exponential values for the s2 matrix
exp(s2)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

#### Round/ceil/floor
<p><h4>the numpy.round() function rounds the elemnent to the nearest integer or to the specified number of decimal points</h4></p>

In [132]:
#round to nearest integer
a=np.random.uniform(1,15,5)
a

array([ 6.98439819, 13.61217949, 11.09208608, 10.46211573,  5.18621572])

In [133]:
round(a)

array([ 7., 14., 11., 10.,  5.])

In [134]:
# returns the smallest integer greater than or equal to the each element of an array
ceil(a)

array([ 7., 14., 12., 11.,  6.])

In [135]:
# returns largest integer less than or equal to each element of an array
floor(a)

array([ 6., 13., 11., 10.,  5.])

### Indexing and slicing

In [136]:
p1=np.arange(10)
p2=np.arange(12).reshape(3,4)
p3=np.arange(8).reshape(2,2,2)

In [137]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [138]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [139]:
p3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

#### indexing on 1D array

In [140]:
p1[1]

np.int64(1)

In [141]:
print(p1[-1])

9


In [142]:
print(p1[1:3])

[1 2]


In [143]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [144]:
print(p1[2::2])   #starts from 2 and continue till last with step value =2

[2 4 6 8]


In [145]:
print(p1[7:3:-1])  # starts with 7th element and decreases by 1 and stops at index 4

[7 6 5 4]


#### indexing on 2D array
<h3>array[rows,columns]</h3>

In [146]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [147]:
p2[1,2]

np.int64(6)

In [148]:
print(p2[1:3]) # starts with first row and ends with second row

[[ 4  5  6  7]
 [ 8  9 10 11]]


In [149]:
print(p2[::2,::3])  #all rows with step value 2, all columns with step value 3

[[ 0  3]
 [ 8 11]]


In [150]:
print(p2[0:2,2:4]) # rows 0,1 and columns 2,3

[[2 3]
 [6 7]]


#### indexing on 3D arrays

In [151]:
p3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [152]:
p3[0,1,1]

np.int64(3)

In [153]:
p3[1]

array([[4, 5],
       [6, 7]])

In [154]:
p4=np.arange(27).reshape(3,3,3)
p4

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [155]:
p4[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [156]:
p4[::2] # all rows with step 2. that means here first and last row

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [157]:
p4[0,1,:]  # 0 means first matrix, 1 represent seconf row, : represents all columns

array([3, 4, 5])

In [158]:
p4[1,:,1]   # 1 represents 1st matrix, : represents all rows, 1 represents 2nd column

array([10, 13, 16])

In [159]:
p4[0::2,0] #here in this two matrices 1,3 are selected and there are twop matrices. So 0 means first row of two matrices

array([[ 0,  1,  2],
       [18, 19, 20]])

#### iterating

In [160]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [161]:
for i in p1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [162]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [163]:
for i in p2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [164]:
p4

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [165]:
for i in p4:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [166]:
# print all items in 2D, 3D array using np.nditer(). It first convert it into 1D array and then apply the loop.
for i in np.nditer(p4):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [167]:
for i in np.nditer(p2):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [168]:
# Transpose can convert rows into columns and columns into rows
transpose(p2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [169]:
p2.T   # it's also gives transpose

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [170]:
p4

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [171]:
p4.T

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

### Ravel
#### Converting any dimensions to 1D array

In [172]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [173]:
ravel(p2)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [174]:
p2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [175]:
p4

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [176]:
ravel(p4)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

#### Stacking
####  stacking is the concept of joining arrays in Numpy. arrays having the same dimensions can be stacked.

In [177]:
w1=np.arange(12).reshape(3,4)
w2=np.arange(12,24).reshape(3,4)

In [178]:
w1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [179]:
w2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [180]:
hstack((w1,w2))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [181]:
vstack((w1,w2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [182]:
#splitting the array
hsplit(w1,2) #split horizontally into two equal parts

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [183]:
vsplit(w2,3)    # splits vertically into 3 equal parts

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

In [184]:
hsplit(w1,4)  #splits horizontally into 4 equal parts

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

### Speed of list vs numpy

In [185]:
# element-wise addition
a=[i for i in range(10000000)]
b=[i for i in range(10000000,20000000)]

c=[]

import time
start= time.time()
for i in range(len(a)):
    c.append(a[i]+b[i])

print(time.time()-start)

1.8961842060089111


In [186]:
import numpy as np
a=np.arange(10000000)
b=np.arange(10000000,20000000)
start=time.time()
c=a+b
print(time.time()-start)

0.15903210639953613


### Memory used for list and numpy

In [187]:
import sys
p=[i for i in range(10000000)]
sys.getsizeof(p)

89095160

In [188]:
a=np.arange(10000000,dtype=np.int16)
sys.getsizeof(a)

20000112

#### Fancy indexing
#### Fancy indexing allows you to select or modify specific elements based on complex conditions or combinations of indices. It provides a prowerful way to manipulate array data in numpy   

In [189]:
w=np.arange(12).reshape(4,3)
w

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [190]:
w[1,2]

np.int64(5)

In [191]:
w[[0,2,3]]  # selecting only 0,2,3 rows

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [192]:
z=np.arange(24).reshape(6,4)
z

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [193]:
z[[0,2,3,5]]   # this is a way of selecting manually which row you need in the matrix

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [194]:
z[:,[0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

#### Boolean indexing
#### It allows you to select elements from an array based on a boolean condition. This allows you to extract only the elements of an array that meet a certain condition, making it easy to perform operations on specific subsets of data.

In [195]:
G=np.random.randint(1,100,24).reshape(6,4)

In [196]:
G

array([[89, 44, 54, 14],
       [98, 58, 65, 62],
       [77, 76, 72, 95],
       [36, 37, 81, 60],
       [73, 84, 99, 57],
       [ 7, 58, 53, 67]], dtype=int32)

In [197]:
#find all numbers greater than 50
G>50

array([[ True, False,  True, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True,  True,  True],
       [False,  True,  True,  True]])

In [198]:
G[G>50]

array([89, 54, 98, 58, 65, 62, 77, 76, 72, 95, 81, 60, 73, 84, 99, 57, 58,
       53, 67], dtype=int32)

In [199]:
G[G%2==0]

array([44, 54, 14, 98, 58, 62, 76, 72, 36, 60, 84, 58], dtype=int32)

In [200]:
#using bitwise AND(&) operator
G[(G>50)&(G%2==0)]

array([54, 98, 58, 62, 76, 72, 60, 84, 58], dtype=int32)

In [201]:
G[~(G%7==0)]  #using(~) not operator

array([89, 44, 54, 58, 65, 62, 76, 72, 95, 36, 37, 81, 60, 73, 99, 57, 58,
       53, 67], dtype=int32)

#### Broadcasting
<p style="color: violet;">Broadcasting in NumPy allows operations on arrays of different shapes by automatically expanding the smaller array to match the shape of the larger one without making extra copies.</p>

<l style="color: yellow;"> * Broad casting rules
* Match dimensions from right to left.
* A dimension of size 1 can be stretched to match the other array.
* Missing dimensions are assumed to be 1.</l>

In [202]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
scalar = 2

result = arr * scalar
print(result)
# The scalar 2 is broadcasted to match the shape (2,3).


[[ 2  4  6]
 [ 8 10 12]]


In [203]:
from numpy import *

In [204]:
arr=array([1,2,3])
scalar=2
arr*scalar

array([2, 4, 6])

In [205]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
row_vector = np.array([10, 20, 30])

result = matrix + row_vector
print(result)
#The row vector [10, 20, 30] is broadcasted to match (2,3).


[[11 22 33]
 [14 25 36]]


In [206]:
col_vector = np.array([[10], [20]])  # Shape (2,1)

result = matrix + col_vector
print(result)
#The column vector [[10], [20]] is broadcasted to (2,3).

[[11 12 13]
 [24 25 26]]


In [207]:
ab=np.array([1,2])  # because it is 1D array. the shape of this is (2,)
ab.shape

(2,)

In [208]:
#mismatched shapes (broadcasting array)
#arr1 = np.array([[1, 2, 3], [4, 5, 6]])  # Shape (2,3)
#arr2 = np.array([1, 2])  # Shape (2,)

#result = arr1 + arr2  # ❌ Error: Shapes (2,3) and (2,) are incompatible

#output

#'''ValueError                                Traceback (most recent call last)
#Cell In[34], line 5
 #     2 arr1 = np.array([[1, 2, 3], [4, 5, 6]])  # Shape (2,3)
  #    3 arr2 = np.array([1, 2])  # Shape (2,)
#-> 5 result = arr1 + arr2  # ❌ Error: Shapes (2,3) and (2,) are incompatible
#
#ValueError: operands could not be broadcast together with shapes (2,3) (2,) '''


#### Mathematical functions

In [209]:
k=np.arange(10)

In [210]:
k

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [211]:
sum(k)

np.int64(45)

In [212]:
print(sin(k))

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]


In [213]:
# sigmoid function


def sigmoid(x):
    a=1/(1+(np.exp(-x)))
    return a

In [214]:
sigmoid(k)

array([0.5       , 0.73105858, 0.88079708, 0.95257413, 0.98201379,
       0.99330715, 0.99752738, 0.99908895, 0.99966465, 0.99987661])

In [215]:
k1=np.arange(100)
sigmoid(k1)

array([0.5       , 0.73105858, 0.88079708, 0.95257413, 0.98201379,
       0.99330715, 0.99752738, 0.99908895, 0.99966465, 0.99987661,
       0.9999546 , 0.9999833 , 0.99999386, 0.99999774, 0.99999917,
       0.99999969, 0.99999989, 0.99999996, 0.99999998, 0.99999999,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.     

#### Mean square error

In [216]:
actual = np.random.randint(1,50,25)
predicted=np.random.randint(1,50,25)


In [217]:
actual

array([ 2, 34,  8, 45,  1, 36, 27, 37, 20,  4,  7, 13, 20, 43, 27, 38, 42,
       35, 19, 32,  6, 20, 28,  1,  6], dtype=int32)

In [218]:
predicted

array([44, 28, 15, 46, 35, 24, 30,  7, 12, 36, 31, 18, 12, 47,  9,  6, 24,
       24, 18, 17, 40,  5, 45, 24, 37], dtype=int32)

In [219]:
def mse(actual,predicted):
    return np.mean((actual-predicted)**2)
mse(actual,predicted)

np.float64(440.28)

In [220]:
actual-predicted

array([-42,   6,  -7,  -1, -34,  12,  -3,  30,   8, -32, -24,  -5,   8,
        -4,  18,  32,  18,  11,   1,  15, -34,  15, -17, -23, -31],
      dtype=int32)

In [221]:
(actual-predicted)**2

array([1764,   36,   49,    1, 1156,  144,    9,  900,   64, 1024,  576,
         25,   64,   16,  324, 1024,  324,  121,    1,  225, 1156,  225,
        289,  529,  961], dtype=int32)

In [222]:
np.mean((actual-predicted)**2)

np.float64(440.28)

#### working with missing values

In [223]:
# working with missing values -> np.nan
S=np.array([1,2,3,4,np.nan,6])
S

array([ 1.,  2.,  3.,  4., nan,  6.])

In [224]:
isnan(S)

array([False, False, False, False,  True, False])

In [225]:
S[isnan(S)]   #Nan values

array([nan])

In [226]:
S[~isnan(S)]   # not nan values

array([1., 2., 3., 4., 6.])

#### np.sort()

In [227]:
a=np.random.randint(1,100,15)
a

array([99,  8, 79, 92,  2, 75, 92,  1, 51,  4,  6, 46,  9, 59, 66],
      dtype=int32)

In [228]:
b=np.random.randint(1,100,24).reshape(6,4)
b

array([[10, 64, 45, 52],
       [81, 12, 97, 62],
       [29, 23, 86, 71],
       [47, 83, 57, 61],
       [49, 55, 72, 25],
       [69, 32, 10, 24]], dtype=int32)

In [229]:
np.sort(a) #default = ascending

array([ 1,  2,  4,  6,  8,  9, 46, 51, 59, 66, 75, 79, 92, 92, 99],
      dtype=int32)

In [230]:
sort(a)[::-1]  #descending order

array([99, 92, 92, 79, 75, 66, 59, 51, 46,  9,  8,  6,  4,  2,  1],
      dtype=int32)

In [231]:
b

array([[10, 64, 45, 52],
       [81, 12, 97, 62],
       [29, 23, 86, 71],
       [47, 83, 57, 61],
       [49, 55, 72, 25],
       [69, 32, 10, 24]], dtype=int32)

In [232]:
sort(b) #default sorting happens row wise

array([[10, 45, 52, 64],
       [12, 62, 81, 97],
       [23, 29, 71, 86],
       [47, 57, 61, 83],
       [25, 49, 55, 72],
       [10, 24, 32, 69]], dtype=int32)

In [233]:
sort(b,axis=0) #column wise sorting

array([[10, 12, 10, 24],
       [29, 23, 45, 25],
       [47, 32, 57, 52],
       [49, 55, 72, 61],
       [69, 64, 86, 62],
       [81, 83, 97, 71]], dtype=int32)

#### np.unique
#### with the help of this method we can get the unique values from the array 

In [234]:
e=array([1,1,2,2,3,3,4,4,5,5,6,6])
unique(e)

array([1, 2, 3, 4, 5, 6])

#### np.expand_dims()
#### with the help of this method , we can get the expanded dimensions of an array

In [235]:
a

array([99,  8, 79, 92,  2, 75, 92,  1, 51,  4,  6, 46,  9, 59, 66],
      dtype=int32)

In [236]:
a.shape

(15,)

In [237]:
#converting a into 2D array
expand_dims(a,axis=0)


array([[99,  8, 79, 92,  2, 75, 92,  1, 51,  4,  6, 46,  9, 59, 66]],
      dtype=int32)

In [238]:
expand_dims(a,axis=0).shape

(1, 15)

In [239]:
expand_dims(a,axis=1)

array([[99],
       [ 8],
       [79],
       [92],
       [ 2],
       [75],
       [92],
       [ 1],
       [51],
       [ 4],
       [ 6],
       [46],
       [ 9],
       [59],
       [66]], dtype=int32)

In [240]:
expand_dims(a,axis=1).shape

(15, 1)

#### np.where()
#### This function returns the indices of elements where the given condition is satisfied
#### np.where(condition,True,false)

In [241]:
where(a>50)

(array([ 0,  2,  3,  5,  6,  8, 13, 14]),)

In [242]:
# where a>50 condition is met, there it is replaced by zero in the matrix a
where(a>50,0,a)

array([ 0,  8,  0,  0,  2,  0,  0,  1,  0,  4,  6, 46,  9,  0,  0],
      dtype=int32)

In [243]:
#where there is even numbers they are replaced by zero in matrix a
where(a%2==0,0,a)

array([99,  0, 79,  0,  0, 75,  0,  1, 51,  0,  0,  0,  9, 59,  0],
      dtype=int32)

### On statistics

In [244]:
#np.cumsum()
#it is used when we need cumulative sum over a given axis
a
cumsum(a)

array([ 99, 107, 186, 278, 280, 355, 447, 448, 499, 503, 509, 555, 564,
       623, 689])

In [245]:
b

array([[10, 64, 45, 52],
       [81, 12, 97, 62],
       [29, 23, 86, 71],
       [47, 83, 57, 61],
       [49, 55, 72, 25],
       [69, 32, 10, 24]], dtype=int32)

In [246]:
cumsum(b)

array([  10,   74,  119,  171,  252,  264,  361,  423,  452,  475,  561,
        632,  679,  762,  819,  880,  929,  984, 1056, 1081, 1150, 1182,
       1192, 1216])

In [247]:
cumsum(b,axis=1)

array([[ 10,  74, 119, 171],
       [ 81,  93, 190, 252],
       [ 29,  52, 138, 209],
       [ 47, 130, 187, 248],
       [ 49, 104, 176, 201],
       [ 69, 101, 111, 135]])

In [248]:
cumsum(b,axis=0)

array([[ 10,  64,  45,  52],
       [ 91,  76, 142, 114],
       [120,  99, 228, 185],
       [167, 182, 285, 246],
       [216, 237, 357, 271],
       [285, 269, 367, 295]])

In [249]:
cumprod(a)

array([                 99,                 792,               62568,
                   5756256,            11512512,           863438400,
               79436332800,         79436332800,       4051252972800,
            16205011891200,      97230071347200,    4472583281971200,
         40253249537740800, 2374941722726707200, 9172201110286262272])

In [250]:
cumprod(b,axis=1)

array([[      10,      640,    28800,  1497600],
       [      81,      972,    94284,  5845608],
       [      29,      667,    57362,  4072702],
       [      47,     3901,   222357, 13563777],
       [      49,     2695,   194040,  4851000],
       [      69,     2208,    22080,   529920]])

In [251]:
cumprod(b,axis=0)

array([[         10,          64,          45,          52],
       [        810,         768,        4365,        3224],
       [      23490,       17664,      375390,      228904],
       [    1104030,     1466112,    21397230,    13963144],
       [   54097470,    80636160,  1540600560,   349078600],
       [ 3732725430,  2580357120, 15406005600,  8377886400]])

#### np.percentile()
#### This function used to compute the nth percentile of the given data (array elements) along the specified axis.

In [252]:
percentile(a,100)  #this means 100th percentile that is the maximum element

np.float64(99.0)

In [253]:
a

array([99,  8, 79, 92,  2, 75, 92,  1, 51,  4,  6, 46,  9, 59, 66],
      dtype=int32)

In [254]:
percentile(a,0)  # this means 0th percentile that is the minimum element

np.float64(1.0)

In [255]:
percentile(a,50)  #this is the 50th percentile that is median

np.float64(51.0)

In [256]:
median(a)

np.float64(51.0)

In [257]:
percentile(a,25)  #25th percentile of the array

np.float64(7.0)

#### np.histogram()
#### numpy has a built-in np.histogram() function which represents the frequency of the data distribution in the graphical form

In [258]:
a

array([99,  8, 79, 92,  2, 75, 92,  1, 51,  4,  6, 46,  9, 59, 66],
      dtype=int32)

In [259]:
histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([6, 0, 0, 0, 1, 2, 1, 2, 0, 3]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [260]:
a

array([99,  8, 79, 92,  2, 75, 92,  1, 51,  4,  6, 46,  9, 59, 66],
      dtype=int32)

In [261]:
a.size

15

#### np.corrcoef()
#### this returns the pearson product moment correlation coefficients

In [262]:
salary=array([20000,40000,25000,35000,60000])
experience=array([1,3,2,4,2])


In [263]:
salary

array([20000, 40000, 25000, 35000, 60000])

In [264]:
experience

array([1, 3, 2, 4, 2])

In [265]:
np.corrcoef(salary,experience)  #correlation coefficient

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### Utility functions

#### np.isin()
#### with the help of this method, we can see that one array having values are checked in a different numpy array having different elements with different sizes

In [266]:
a

array([99,  8, 79, 92,  2, 75, 92,  1, 51,  4,  6, 46,  9, 59, 66],
      dtype=int32)

In [267]:
items=[10,20,30,40,50,60,70,80,90]

In [268]:
np.isin(a,items)  #checks array a wheter the elements of the array items are present or not. Only 50 is present so only one True

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [269]:
a[isin(a,items)]

array([], dtype=int32)

#### np.flip()
#### This function reverses the order of array elements along the specified axis, preserving the shape of the array

In [270]:
a

array([99,  8, 79, 92,  2, 75, 92,  1, 51,  4,  6, 46,  9, 59, 66],
      dtype=int32)

In [271]:
flip(a)

array([66, 59,  9, 46,  6,  4, 51,  1, 92, 75,  2, 92, 79,  8, 99],
      dtype=int32)

In [272]:
b

array([[10, 64, 45, 52],
       [81, 12, 97, 62],
       [29, 23, 86, 71],
       [47, 83, 57, 61],
       [49, 55, 72, 25],
       [69, 32, 10, 24]], dtype=int32)

In [273]:
flip(b,axis=1)

array([[52, 45, 64, 10],
       [62, 97, 12, 81],
       [71, 86, 23, 29],
       [61, 57, 83, 47],
       [25, 72, 55, 49],
       [24, 10, 32, 69]], dtype=int32)

In [274]:
flip(b,axis=0)

array([[69, 32, 10, 24],
       [49, 55, 72, 25],
       [47, 83, 57, 61],
       [29, 23, 86, 71],
       [81, 12, 97, 62],
       [10, 64, 45, 52]], dtype=int32)

#### np.put()
#### This function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array

In [275]:
a

array([99,  8, 79, 92,  2, 75, 92,  1, 51,  4,  6, 46,  9, 59, 66],
      dtype=int32)

In [276]:
put(a,[0,1],[110,530]) 
# In matrix a at the locations of indices 0&1, elements 110,530 are replaced

In [277]:
a

array([110, 530,  79,  92,   2,  75,  92,   1,  51,   4,   6,  46,   9,
        59,  66], dtype=int32)

#### np.delete
#### This function returns a new array with the deletion of the sub arrays along with the mentioneds axis

In [278]:
a

array([110, 530,  79,  92,   2,  75,  92,   1,  51,   4,   6,  46,   9,
        59,  66], dtype=int32)

In [279]:
np.delete(a,0)

array([530,  79,  92,   2,  75,  92,   1,  51,   4,   6,  46,   9,  59,
        66], dtype=int32)

In [280]:
np.delete(a,[0,2,4])

array([530,  92,  75,  92,   1,  51,   4,   6,  46,   9,  59,  66],
      dtype=int32)

#### set functions


In [281]:
m=array([1,2,3,4,5])
n=array([3,4,5,6,7])

In [282]:
union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [283]:
intersect1d(m,n)

array([3, 4, 5])

In [284]:
setdiff1d(n,m)

array([6, 7])

In [285]:
setxor1d(m,n)   # xor operation

array([1, 2, 6, 7])

In [286]:
isin(m,1)  #membership operator

array([ True, False, False, False, False])

#### np.clip()
#### it is used to clip(limit) the values in an array

In [287]:
a

array([110, 530,  79,  92,   2,  75,  92,   1,  51,   4,   6,  46,   9,
        59,  66], dtype=int32)

In [288]:
clip(a,a_min=15,a_max=50)
#It clips the minimum data to 15 and replaces everything below data to 15 and maximum to 50

array([50, 50, 50, 50, 15, 50, 50, 15, 50, 15, 15, 46, 15, 50, 50],
      dtype=int32)

#### np.swapaxes()
#### this function interchanges two axes of an array

In [289]:
arr=np.array([[1,2,3],[4,5,6]])
swapped_arr= swapaxes(arr,0,1)

In [290]:
arr  #shape is (2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [291]:
swapped_arr   #shape is (3,2)

array([[1, 4],
       [2, 5],
       [3, 6]])

### Universal Functions

In [292]:
a=np.array([10,20,30])

In [293]:
exp(a)

array([2.20264658e+04, 4.85165195e+08, 1.06864746e+13])

In [294]:
sqrt(a)

array([3.16227766, 4.47213595, 5.47722558])

In [295]:
y=array([24,56,7])
add(a,y)

array([34, 76, 37])

### Numpy data types

In [296]:
a=array(['data','science','teha','teja'])
b=array([1,2,3,45])
c=array([1.0,4,5.3])
d=array([True,False])
e=array([1+5j])

In [297]:
print(f'data type of array a: {a.dtype}')
print(f'data type of array b: {b.dtype}')
print(f'data type of array c: {c.dtype}')
print(f'data type of array d: {d.dtype}')
print(f'data type of array e: {e.dtype}')


data type of array a: <U7
data type of array b: int64
data type of array c: float64
data type of array d: bool
data type of array e: complex128


<p><h2 style="color:yellow;"> numpy arrays are mutable </h2></p>

In [298]:

zero= zeros((5,5),dtype='int16')
zero[2,2]=5   # it replaces 0 with 5 at row=2 and column=2
print(zero)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 5 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [299]:
three= zeros((3,3))
three[1,1]=5
inone=ones((5,5))
inone[1:-1,1:4]=three     # this inserts the array three in the inone array at rows starting at 1 till last and columns starting at 1
#and continues till 3rd column
print(f"zeroes with 5\n\n {three}\n")
print(f"ones and zeroes with 5\n\n {inone}")

zeroes with 5

 [[0. 0. 0.]
 [0. 5. 0.]
 [0. 0. 0.]]

ones and zeroes with 5

 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 5. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [300]:
empty_arr=empty((2,3))    #empty function generates random values
empty_arr

array([[-1.41628017e-311,  3.98242539e-309,  1.41628156e-311],
       [ 1.41628156e-311,  1.48219694e-323,  1.67982320e-322]])

In [301]:
# numpy zeroes like 
x_like=np.arange(9).reshape(3,3)
x_like

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [302]:
zeros_like=np.zeros_like(x_like)   #this function makes all the values lokks like zeroes
zeros_like

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [303]:
#numpy.ones_like()
ones=np.ones_like(x_like)  #this function makes all the values into ones
ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [304]:
#np.full_like()
full=np.full_like(x_like,5)   # this function makes all the values into the entered value
full

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

### Numpy Trigonometric functions
#### Numpy provides the ufuncs sin(),cos(), tan() that takes values in radians and produce the corresponding sin,cos,tan values

In [305]:
sin(pi/2)

np.float64(1.0)

In [306]:
pi2=array([pi/2,pi/3,pi/4,pi/5])
sin(pi2)

array([1.        , 0.8660254 , 0.70710678, 0.58778525])

In [307]:
# convert degrees into radians
a=array([90,180,270,360])
deg2rad(a)

array([1.57079633, 3.14159265, 4.71238898, 6.28318531])

In [308]:
#radians to degrees
a=array([90,180,270,360])
rad2deg(a)

array([ 5156.62015618, 10313.24031235, 15469.86046853, 20626.48062471])

#### inverse functions arcsin(), arccos(), arctan()

In [309]:
arcsin(1.0)   #this output is equal to the pi/2 value

np.float64(1.5707963267948966)

In [310]:
pi/2

1.5707963267948966

In [311]:
arcsin([1,-1])

array([ 1.57079633, -1.57079633])

In [312]:
#hypotenuse
a=3
b=4
hypot(a,b)

np.float64(5.0)

In [313]:
a=20
b=25
hypot(a,b)

np.float64(32.01562118716424)

#### hyperbolic functions
#### sinh(),cosh(),tanh()... are hyperbolic functions

In [314]:
sinh(pi/2)

np.float64(2.3012989023072947)

In [315]:
#inverse hyperbolic functions
arcsinh(1.0)

np.float64(0.881373587019543)

In [316]:
#greatest common divisor(gcd)
a=6
b=9
gcd(a,b)

np.int64(3)

In [317]:
arr=array([20,8,32,36,16])
gcd.reduce(arr)

np.int64(4)

In [318]:
#least common multiple
#lcm is the smallest number that is a common multiple of two numbers.
n1=4
n2=6
lcm(n1,n2)

np.int64(12)

In [319]:
#reduce() method will use the ufunc, in this case the lcm() function, on each element, and reduce the array by one dimension.
a=np.array([3,6,9])
lcm.reduce(a)

np.int64(18)

#### NumPy logs

In [320]:
ab=arange(1,12)
log(ab)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527])

In [321]:
log2(ab)

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809,
       2.5849625 , 2.80735492, 3.        , 3.169925  , 3.32192809,
       3.45943162])

In [322]:
log10(ab)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ,
       1.04139269])

In [323]:
#truncate function
trunc([-3.1666,3.6667])

array([-3.,  3.])

In [324]:
fix([-3.1666,3.6667])

array([-3.,  3.])

In [325]:
#around , this function gives the nearest integer
around([-3.1666,3.6667])

array([-3.,  4.])

#### Arithmetic functions

In [326]:
a=np.arange(1,12)
b=np.arange(12,23)
print(f'addition of two numbers:{add(a,b)}')

addition of two numbers:[13 15 17 19 21 23 25 27 29 31 33]


In [327]:
print(a)
print('\n')
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11]


[12 13 14 15 16 17 18 19 20 21 22]


In [328]:
print(f'subtraction of two numbers:{subtract(b,a)}')
print('\n')
print(f'multiplication of two arrays:{multiply(a,b)}')
print('\n')
print(f'division of two arrays:{divide(b,a)}')     # gives the float number by which the number is exactly divisible
print('\n')
print(f'power of elements in two arrays:{power(a,b)}')
print('\n')
print(f'modulus of two arrays:{mod(a,b)}')     # mod function gives remainder
print('\n')
print(f'remainder of two arrays:{remainder(b,a)}')    #remainder function gives remainder. Both mod and remainder gives the same output
print('\n')                                           #but when you are dealing with the negative values both gives different output
print(f'quotient of two arrays:{floor_divide(b,a)}')                                                      

subtraction of two numbers:[11 11 11 11 11 11 11 11 11 11 11]


multiplication of two arrays:[ 12  26  42  60  80 102 126 152 180 210 242]


division of two arrays:[12.          6.5         4.66666667  3.75        3.2         2.83333333
  2.57142857  2.375       2.22222222  2.1         2.        ]


power of elements in two arrays:[                   1                 8192              4782969
           1073741824         152587890625       16926659444736
     1628413597910449   144115188075855872 -6289078614652622815
  3875820019684212736 -2732210440490168087]


modulus of two arrays:[ 1  2  3  4  5  6  7  8  9 10 11]


remainder of two arrays:[0 1 2 3 1 5 4 3 2 1 0]


quotient of two arrays:[12  6  4  3  3  2  2  2  2  2  2]


In [329]:
10**21

1000000000000000000000

In [330]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [331]:
b


array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22])

In [332]:
p1=array([10,20,30,40])
p2=array([3,4,6,7])
print(mod(p1,p2))
print(remainder(p1,p2))

[1 0 0 5]
[1 0 0 5]


In [333]:
print(a)
print(b)
print('\n')
print(f'power of : {power(a,b,dtype=object)}')

#here if you use dtype=int64, the integers can overflow and gives the negative values. So you need to use dtype=object while computing
#larger powers

[ 1  2  3  4  5  6  7  8  9 10 11]
[12 13 14 15 16 17 18 19 20 21 22]


power of : [1 8192 4782969 1073741824 152587890625 16926659444736 1628413597910449
 144115188075855872 12157665459056928801 1000000000000000000000
 81402749386839761113321]


#### numpy ufuncs

In [334]:
#using normal loops in python
x=[1,2,3,4]
y=[4,5,6,7]
z=[]
for i,j in zip(x,y):
    z.append(i+j)
print(z)

[5, 7, 9, 11]


In [335]:
# using numpy functions
add(x,y)

array([ 5,  7,  9, 11])

In [336]:
def myadd(x,y):
    return x+y
myadd(2,1)

3

In [337]:
myadd(array([1,2,3]),array([4,5,6]))

array([5, 7, 9])

#### Numpy array join

In [338]:
a=array([1,2,3])
b=array([4,5,6])
concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

In [339]:
c=array([[1,2],[3,4]])
d=array([[5,6],[7,8]])
concatenate((c,d))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [340]:
concatenate((c,d),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [341]:
#stack function
stack((c,d))

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [342]:
c

array([[1, 2],
       [3, 4]])

In [343]:
d

array([[5, 6],
       [7, 8]])

In [344]:
hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [345]:
hstack((c,d))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [346]:
vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [347]:
vstack((c,d))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

#### numpy array split

In [348]:
a=array([1,2,3,4,5,6])
array_split(a,2)    #this function can split the array into two equal parts

[array([1, 2, 3]), array([4, 5, 6])]

In [349]:
array_split(a,3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [350]:
array_split(a,4)

[array([1, 2]), array([3, 4]), array([5]), array([6])]

In [351]:
#2D array split
w=arange(16).reshape(4,4)
w

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [352]:
array_split(w,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [353]:
array_split(w,3)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [354]:
array_split(w,6)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]]),
 array([], shape=(0, 4), dtype=int64),
 array([], shape=(0, 4), dtype=int64)]

In [355]:
hsplit(w,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [356]:
vsplit(w,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [357]:
w

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])